FROM wileyj/stacks-blockchain-api:render
# ARG PG_HOST=postgres
# ARG PG_PORT=5432 
# ARG PG_USER=postgres
# ARG PG_PASSWORD=postgres
# ARG PG_DATABASE=postgres
# ARG STACKS_NETWORK=mocknet
# ARG STACKS_BLOCKCHAIN_API_PORT=3999

# ENV PG_HOST=${PG_HOST}
# ENV PG_PORT=${PG_PORT} 
# ENV PG_USER=${PG_USER}
# ENV PG_PASSWORD=${PG_PASSWORD}
# ENV PG_DATABASE=${PG_DATABASE}
# ENV STACKS_NETWORK=${STACKS_NETWORK}
# ENV STACKS_BLOCKCHAIN_API_PORT=${STACKS_BLOCKCHAIN_API_PORT}


# EXPOSE ${STACKS_BLOCKCHAIN_API_PORT}
# EXPOSE 20443
# EXPOSE 20444
# EXPOSE 80
# CMD ["/entrypoint.sh"]

