#!/bin/sh
exec 2>&1

if [ ! -z "${BNS_IMPORT_DIR}" ]; then
    if [ ! -f "${BNS_IMPORT_DIR}/imported" ]; then
        /setup-bns.sh
    fi
fi

case $STACKS_NETWORK in
    mainnet)
        export STACKS_CHAIN_ID=0x00000001
        ;;
    testnet)
        export STACKS_CHAIN_ID=0x80000000
        ;;
    *)
        export STACKS_CHAIN_ID=2147483648
        ;;
esac
cd /app && exec node ./lib/index.js 2>&1